### ISSUE TITLE
Can I deploy it on Streamlit?

### ISSUE THREAD

**Issue by KalvinThien** [grumpyp/blogging-with-ai#2]
I want to have 1 website to access and work right on the phone for simpler :D. Is that possible?

**Comment by grumpyp** [comment]
hello,

you might check https://app.wordgenie.de

**Comment by KalvinThien** [comment]
Thank you so much, I'm having trouble connecting in. 
I followed the video but there is 1 error message as shown below. Can you take a look at it for me?
![image](https://github.com/grumpyp/blogging-with-ai/assets/120565705/2de6cdca-38f5-443c-8a1d-be4937a83cd8)

**Comment by grumpyp** [comment]
Hi, seems like the last `/` of the host is too much.

**Comment by KalvinThien** [comment]
I discovered a residual of 1"/" however still similar. 
I am using CentOS script to do 1 VPS webserver. 
I also tried tweaking the htaccess file, but still couldn't connect.
Is there another way to connect?
